version: '3.8'
services:
  k12-app:
    image: k12
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://k12-postgresql:5432/k12
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://k12-postgresql:5432/k12
      - APPLICATION_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - "127.0.0.1:8080:8080"
