version: '3.8'
services:
  k12-postgresql:
    image: postgres:13.4
    volumes:
      - ~/volumes/application/k12/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=k12
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "127.0.0.1:5432:5432"
