version: '3.8'
services:
  k12-sonar:
    image: sonarqube:8.9.2-community
    # Authentication is turned off for out of the box experience while trying out SonarQube
    # For real use cases delete sonar.forceAuthentication variable or set sonar.forceAuthentication=true
    environment:
      - sonar.forceAuthentication=false
    ports:
      - '127.0.0.1:9001:9000'
